FROM node:19.2
# SET work dir in container
WORKDIR /app
# copy packages files
COPY package.json .
COPY package-lock.json .
# install packages
RUN npm ci --silent
# COPY APP (without .dockerignore)
COPY . .
# Environment Variables
ARG REACT_APP_BACKEND_URL
ENV REACT_APP_BACKEND_URL=$REACT_APP_BACKEND_URL
# RUN the App
EXPOSE 3000
CMD ["npm", "start"]
