version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: DOCKERFILE
    image: slab-uno
    restart: unless-stopped
    container_name: slab-uno-frontend
    ports:
      - "8080:80"
