FROM node:19.2
# SET work dir in container
WORKDIR /app
# copy packages files
COPY package.json .
COPY package-lock.json .
# install packages
RUN npm ci --silent
# COPY APP (without .dockerignore)
COPY . .

# Environment Variables
ENV DOT_ENV_PATH=/app/.env
ENV ENV_JS_PATH=/app/public/env.js

# Make our shell script executable
RUN chmod +x env.sh

# RUN the App
EXPOSE 3000
CMD ["/bin/bash", "-c", "/app/env.sh && npm start"]
