FROM node:19.2
# SET work dir in container
WORKDIR /app
# copy packages files
COPY package.json .
COPY package-lock.json .
# install packages
RUN npm ci --silent
# COPY APP (without .dockerignore)
COPY . .

# Make our shell script executable
RUN chmod +x env-dev.sh

# RUN the App
EXPOSE 3000
CMD ["/bin/bash", "-c", "/app/env-dev.sh && npm start"]
