version: '3.8'

services:
  frontend:
    build:
      context: client
      dockerfile: DOCKERFILE.dev
    image: dasultras/slab-uno:frontend-latest
    restart: unless-stopped
    volumes:
      - ./client/src:/app/src
    environment:
      - WATCHPACK_POLLING=true
      - BACKEND_URL=http://localhost:8080
    ports:
      - "3000:3000"
  backend:
    build:
      context: server
      dockerfile: DOCKERFILE
    image: dasultras/slab-uno:backend-latest
    restart: unless-stopped
    environment:
      - WATCHPACK_POLLING=true
      - FRONTEND_URL=http://localhost:3000
    volumes:
      - ./server/src:/app/src
    ports:
      - "8080:80"
