version: '3.8'

services:
  frontend:
    build:
      context: client
      dockerfile: DOCKERFILE.dev
    image: dasultras/slab-uno-frontend
    restart: unless-stopped
    volumes:
      - ./client/src:/app/src
    environment:
      - WATCHPACK_POLLING=true
      - REACT_APP_BACKEND_URL=http://localhost:8080
#    env_file:
#      - ./client/.env
    ports:
      - "3000:3000"
  backend:
    build:
      context: server
      dockerfile: DOCKERFILE
    image: dasultras/slab-uno-backend
    restart: unless-stopped
    environment:
      - WATCHPACK_POLLING=true
      - FRONTEND_URL=http://localhost:3000
#    env_file:
#      - ./server/.env
    volumes:
      - ./server/src:/app/src
    ports:
      - "8080:8080"
