version: '3.8'

services:
  frontend:
    build:
      context: client
      dockerfile: DOCKERFILE.prod
      args:
        - REACT_APP_BACKEND_URL=http://localhost:8081
    image: dasultras/slab-uno-frontend
    restart: unless-stopped
    ports:
      - "8080:80"
  backend:
    build:
      context: server
      dockerfile: DOCKERFILE
    image: dasultras/slab-uno-backend
    restart: unless-stopped
    environment:
      - FRONTEND_URL=http://localhost:8080
    ports:
      - "8081:8080"
