version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: DOCKERFILE
    image: slab-uno-server
    restart: unless-stopped
    container_name: slab-uno-backend
    ports:
      - "8081:8080"
