FROM node:16
# SET work dir in container
WORKDIR /usr/src/app
# copy packages files
COPY package.json .
COPY package-lock.json .
# install packages
RUN npm ci --silent
# COPY APP (without .dockerignore)
COPY . .
# RUN the App
EXPOSE 3003
CMD ["node", "index.js"]
