FROM node:19.2
# SET work dir in container
WORKDIR /app
# copy packages files
COPY package.json .
COPY package-lock.json .
# install packages
RUN npm ci --silent
# COPY APP (without .dockerignore)
COPY . .
# RUN the App
EXPOSE 80
CMD ["node", "index.js"]
