version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: DOCKERFILE
    image: dasultras/slab-uno:backend-latest
    restart: unless-stopped
    environment:
      - WATCHPACK_POLLING=true
      - FRONTEND_URL=http://localhost:3000
    volumes:
      - ./src:/app/src
    ports:
      - "8080:80"
